-
  name: This is our first play
  hosts: target1
  vars:
    age: 19
  tasks:
    -
      name: "crate a dummy file on target1 machine"
      command: touch /tmp/18.txt
      when: age == 18
    -
      name: "crate a dummy file on target1 machine"
      command: touch /tmp/greater_than_18.txt
      when: age > 18

