-
  name: strategy demo
  hosts: target1
  strategy: linear
  tasks:
    -
      name: 'first task'
      command: touch /tmp/task/task1.txt
      ignore_errors: True
    -
      name: 'second task'
      command: touch /tmp/task2.txt
