-
  name: Test Connectivity
  hosts: target1
  vars:
    ansible_ssh_pass: "{{ lookup('csvfile', 'target1 file=credentials.csv delimiter=,') }}"
  tasks:
  - name: create a dummy file on target1
    command: touch /tmp/csv_lookups.txt
